# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rendered_body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
