# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-08 21:50
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F


def migrate_categories(*args):
    from authentication.models import User
    from treasurer.models import Category, Transaction
    for user in User.objects.all():
        max_id = Category.objects.order_by('-id').first().id
        categories = [c.get_descendants(include_self=True).values()
                      for c in Category.objects.filter(parent__isnull=True, user__isnull=True)]
        for each in categories:
            for category in each:
                id_ = max_id + category['id']
                parent_id = None
                if category.get('parent_id'):
                    parent_id = max_id + category['parent_id']
                Category.objects.create(
                    id=id_,
                    user=user,
                    parent_id=parent_id,
                    name=category['name']
                )

        Transaction.objects.filter(user=user).update(category_id=F('category_id') + max_id)


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0003_category_user'),
    ]

    operations = [
        migrations.RunPython(migrate_categories),
    ]
