# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurer', '0005_transaction_destination_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='destination_account',
        ),
    ]
